repos:
- repo: https://github.com/kynan/nbstripout
  rev: 0.8.2
  hooks:
    - id: nbstripout
- repo: local
  hooks:
    - id: ruff-format
      name: Ruff format python code
      entry: ruff format
      language: python
      types: [python, jupyter, pyi]
    - id: ruff-lint
      name: Ruff lint
      entry: ruff check
      language: python
      types: [python, jupyter, pyi]
