[project]
name = "vpop-calibration"
version = "4.6.8"
description = ""
authors = [{ name = "Paul Lemarre", email = "paul.lemarre@novainsilico.ai" }]
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = ["torch", "scipy", "uuid", "pandas", "numpy", "pydantic", "pandera"]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cpu" }]

[project.optional-dependencies]
full = ["gpytorch", "matplotlib","libroadrunner", "tqdm","plotnine"]

[dependency-groups]
dev = ["ipykernel", "ipython","jupyter"]
test = ["pytest","pytest-cov","pytest-env","pytest-profiling","pre-commit","pytest-subtests","py-spy","pytest-golden","deepdiff","nbmake"]
test_slim = ["pytest", "pytest-env"]

[build-system]
requires = ["uv_build>=0.11,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[tool.pytest]
minversion = "9.0"
addopts = [
    "-ra",
    "-q",
    "--cov=vpop_calibration",
    "--cov-report=markdown",
    "--nbmake",
    "--nbmake-timeout=100",
    "--profile",
    "--durations=5",
]
testpaths = ["vpop_calibration/test", "examples"]
filterwarnings = ["error", "ignore::UserWarning", "ignore::DeprecationWarning"]
env = ["IS_PYTEST_RUNNING=True", "CUDA_VISIBLE_DEVICES=", "MPLBACKEND=agg"]
enable_assertion_pass_hook = true

[tool.coverage.run]
branch = true
omit = ["vpop_calibration/test/*"]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_also = [
    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self\\.debug",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",

    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
]
show_missing = true
ignore_errors = true

[tool.ruff.lint]
ignore = ["F403", "F405"]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff]
exclude = [".venv*"]
