from pathlib import Path

import numpy as np
import pandas as pd
import pytest
import torch
from deepdiff import DeepDiff

import vpop_calibration.saem.optimizer as saem_optimizer
from vpop_calibration.api import (
    Config,
    NlmeConfigDict,
    NlmeModel,
    SaemConfigDict,
    StructuralAnalytical,
)

# Mirrors examples/benchmarking/benchmark_fixed_effects.ipynb.
PERIOD = 24.0
MI_NAMES = [f"mi_{j}" for j in range(1, 6)]
TRUE_MI = dict(zip(MI_NAMES, [0.25, 0.18, 0.15, 0.12, 0.08], strict=True))


def compare_estimate(estimated: float, reference: float, reference_name: str) -> dict:
    return {
        reference_name: reference,
        "estimated": estimated,
        "relative_error_pct": 100.0 * (estimated / reference - 1.0),
    }


@pytest.fixture
def benchmark_data() -> pd.DataFrame:
    # Fixed observations generated by the benchmark notebook (simulation seed 2026).
    return pd.read_csv(Path(__file__).parent / "assets" / "fixed_effects_data.csv")


@pytest.fixture
def obs_data(benchmark_data) -> pd.DataFrame:
    return benchmark_data[["id", "time", "protocol_arm", "output_name", "value"]]


@pytest.fixture
def struct_model() -> StructuralAnalytical:
    def periodic_signal(amplitude, mi_1, mi_2, mi_3, mi_4, mi_5, t):
        u = 2.0 * torch.pi * t / PERIOD
        return amplitude * (
            1.0
            + mi_1 * torch.cos(u)
            + mi_2 * torch.sin(u)
            + mi_3 * torch.cos(2.0 * u)
            + mi_4 * torch.sin(2.0 * u)
            + mi_5 * torch.cos(3.0 * u)
        )

    return StructuralAnalytical(periodic_signal, ["signal"])


@pytest.fixture
def synthetic_config() -> Config:
    return Config(
        seed=2027,
        nlme=NlmeConfigDict(nb_chains=5, live_plot=False, progress_bar=False),
        saem=SaemConfigDict(
            nb_iter_burnin=10,
            nb_iter_learning=90,
            nb_iter_smoothing=50,
            nb_mcmc_transitions=3,
            annealing_factor=0.95,
            fixed_effects_nb_iter=5,
            fixed_effects_lr=2e-2,
            fixed_effects_grad_scale=1e-3,
            learning_rate_power=0.5,
            live_plot=False,
            progress_bars=False,
            logging=False,
        ),
    )


@pytest.fixture
def model_params() -> dict:
    return {
        "pdu": {"amplitude": {"prior": 1.5, "prior_omega": 0.5**2}},
        "model_intrinsic": {
            "mi_1": {"prior": 0.015},
            "mi_2": {"prior": 0.25},
            "mi_3": {"prior": 0.08},
            "mi_4": {"prior": 0.20},
            "mi_5": {"prior": 0.12},
        },
        "error_model": {
            "signal": {"error_type": "additive", "initial_variance": 0.2**2}
        },
    }


@pytest.mark.golden_test("stored_results/test_fixed_effects.yml")
def test_fixed_effects_golden(
    benchmark_data,
    obs_data,
    struct_model,
    synthetic_config,
    model_params,
    monkeypatch,
    golden,
    request,
):
    # Run the full benchmark schedule rather than the shortened pytest schedule.
    monkeypatch.setattr(saem_optimizer, "smoke_test", False)

    nlme_model = NlmeModel(
        structural_model=struct_model,
        df=obs_data,
        input_params=model_params,
        config=synthetic_config,
    )
    nlme_model.optimizer.run()

    model = nlme_model.statistical_model
    mi_values = (
        model.mi_transform(model.log_mi[None, None, :]).detach().cpu().numpy()[0, 0]
    )
    estimated_mi = dict(zip(MI_NAMES, mi_values.tolist(), strict=True))
    log_amplitude_mean = model.population_betas[0].item()
    log_amplitude_variance = model.omega_pop[0, 0].item()
    residual_variance = model.residual_var.additive_variance[0].item()

    amplitudes_by_patient = benchmark_data.groupby("id")["true_amplitude"]
    realized_log_amplitudes = np.log(amplitudes_by_patient.first().to_numpy())
    realized_noise = (
        benchmark_data["value"] - benchmark_data["true_signal"]
    ).to_numpy()

    actual = {
        "parameter_estimates": {
            "log_amplitude_mean": log_amplitude_mean,
            "log_amplitude_variance": log_amplitude_variance,
            "model_intrinsic": estimated_mi,
            "residual_variance": residual_variance,
        },
        "parameter_comparison": {
            "model_intrinsic": {
                name: compare_estimate(estimated_mi[name], true_value, "true")
                for name, true_value in TRUE_MI.items()
            },
            "amplitude_mean": compare_estimate(
                log_amplitude_mean, float(realized_log_amplitudes.mean()), "realized"
            ),
            "amplitude_variance": compare_estimate(
                log_amplitude_variance,
                float(realized_log_amplitudes.var(ddof=1)),
                "realized",
            ),
            "residual_variance": compare_estimate(
                residual_variance, float(realized_noise.var(ddof=1)), "realized"
            ),
        },
        "state": nlme_model.get_state_dict(),
    }
    expected = golden.out["output"]

    if request.config.getoption("--update-goldens"):
        assert actual == expected
    else:
        diff = DeepDiff(
            actual,
            expected,
            ignore_type_in_groups=[(tuple, list), (float, np.float64)],
            math_epsilon=1e-16,
            ignore_nan_inequality=True,
        )
        assert diff == {}
